-- DDL: TB_DISCIPLNAS

DROP TABLE IF EXISTS TB_DISCIPLINAS;

CREATE TABLE TB_DISCIPLINAS (
	ID_DISCIPLINA VARCHAR(10) PRIMARY KEY,
	DISCIPLINA VARCHAR(MAX) NOT NULL
);


-- EXATAS
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('MAT', 'Matem�tica');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('FIS', 'F�sica');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('QUI', 'Qu�mica');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('CIE', 'Ci�ncias');

-- HUMANAS
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('HIS', 'Hist�ria');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('GEO', 'Geografia');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('FIL', 'Filosofia');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('SOC', 'Sociologia');

-- L�NGUAS
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('POR', 'Portugu�s');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('ING', 'Ingl�s');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('ESP', 'Espanhol');

-- EXTRAS
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('EDF', 'Educa��o F�sica');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('INF', 'Inform�tica');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('ART', 'Educa��o Art�stica');

-- Visualisando a tabela
SELECT * FROM TB_DISCIPLINAS;
