-- DDL: TB_ALUNOS

DROP TABLE IF EXISTS TB_ALUNOS;

CREATE TABLE TB_ALUNOS (
	RA_ALUNO CHAR(11) PRIMARY KEY,
	NOME_ALUNO VARCHAR(255) NOT NULL,
	DT_NASCIMENTO DATE NOT NULL,
	RG_ALUNO VARCHAR(12) NOT NULL UNIQUE,
	-- UF_NASCIMENTO CHAR(2) NOT NULL,
	CPF_ALUNO VARCHAR(14) NOT NULL UNIQUE,
	NOME_MAE VARCHAR(255) NOT NULL,
	NOME_PAI VARCHAR(255) NOT NULL
);
