-- DDL: TABELA PERÍODOS TURMAS

DROP TABLE IF EXISTS TB_PERIODOS_TURMAS;

CREATE TABLE TB_PERIODOS_TURMAS (
	ID_PERIODO_TURMA CHAR(3) PRIMARY KEY,
	PERIODO_TURMA VARCHAR(MAX)
);


-- Inserindo os Períodos
INSERT INTO TB_PERIODOS_TURMAS (ID_PERIODO_TURMA, PERIODO_TURMA) VALUES ('INT', 'Integral');
INSERT INTO TB_PERIODOS_TURMAS (ID_PERIODO_TURMA, PERIODO_TURMA) VALUES ('MAT', 'Matutino');
INSERT INTO TB_PERIODOS_TURMAS (ID_PERIODO_TURMA, PERIODO_TURMA) VALUES ('VES', 'Vespertino');
INSERT INTO TB_PERIODOS_TURMAS (ID_PERIODO_TURMA, PERIODO_TURMA) VALUES ('NOT', 'Noturno');

-- Verificando a tabela
SELECT * FROM TB_PERIODOS_TURMAS;