-- DDL: TB_DISCIPLNAS

DROP TABLE IF EXISTS TB_DISCIPLINAS;

CREATE TABLE TB_DISCIPLINAS (
	ID_DISCIPLINA VARCHAR(10) PRIMARY KEY,
	DISCIPLINA VARCHAR(MAX) NOT NULL
);


-- EXATAS
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('MAT', 'Matemática');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('FIS', 'Física');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('QUI', 'Química');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('CIE', 'Ciências');

-- HUMANAS
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('HIS', 'História');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('GEO', 'Geografia');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('FIL', 'Filosofia');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('SOC', 'Sociologia');

-- LÍNGUAS
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('POR', 'Português');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('ING', 'Inglês');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('ESP', 'Espanhol');

-- EXTRAS
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('EDF', 'Educação Física');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('INF', 'Informática');
INSERT INTO TB_DISCIPLINAS (ID_DISCIPLINA, DISCIPLINA) VALUES ('ART', 'Educação Artística');

-- Visualisando a tabela
SELECT * FROM TB_DISCIPLINAS;
