-- DDL: TABELA PERÍODOS
DROP TABLE IF EXISTS TB_PERIODOS;

CREATE TABLE TB_PERIODOS(
		ID_PERIODO CHAR(3) PRIMARY KEY,
		PERIODO VARCHAR(MAX) NOT NULL
);

-- Bimestres
INSERT INTO TB_PERIODOS (ID_PERIODO, PERIODO) VALUES ('1B', '1º Bimestre');
INSERT INTO TB_PERIODOS (ID_PERIODO, PERIODO) VALUES ('2B', '2º Bimestre');
INSERT INTO TB_PERIODOS (ID_PERIODO, PERIODO) VALUES ('3B', '3º Bimestre');
INSERT INTO TB_PERIODOS (ID_PERIODO, PERIODO) VALUES ('4B', '4º Bimestre');

-- Trimestre
INSERT INTO TB_PERIODOS (ID_PERIODO, PERIODO) VALUES ('1T', '1º Trimestre');
INSERT INTO TB_PERIODOS (ID_PERIODO, PERIODO) VALUES ('2T', '2º Trimestre');
INSERT INTO TB_PERIODOS (ID_PERIODO, PERIODO) VALUES ('3T', '3º Trimestre');
INSERT INTO TB_PERIODOS (ID_PERIODO, PERIODO) VALUES ('4T', '4º Trimestre');

-- Semestres
INSERT INTO TB_PERIODOS (ID_PERIODO, PERIODO) VALUES ('1S', '1º Semestre');
INSERT INTO TB_PERIODOS (ID_PERIODO, PERIODO) VALUES ('2S', '2º Semestre');

-- Verificando a tabela
SELECT * FROM TB_PERIODOS;