-- DDL: TABELA TURMAS

DROP TABLE IF EXISTS TB_TURMAS;

CREATE TABLE TB_TURMAS (
	ID_TURMA CHAR(3) PRIMARY KEY,
	TURMA VARCHAR(MAX) NOT NULL,
);

-- EDUCAÇÃO INFANTIL
INSERT INTO TB_TURMAS (ID_TURMA, TURMA) VALUES ('MMT', 'Mini-Maternal');
INSERT INTO TB_TURMAS (ID_TURMA, TURMA) VALUES ('MAT', 'Maternal');
INSERT INTO TB_TURMAS (ID_TURMA, TURMA) VALUES ('PR1', 'Pré-1');
INSERT INTO TB_TURMAS (ID_TURMA, TURMA) VALUES ('PR2', 'Pré-2');

-- ENSINO FUNDAMENTAL I
INSERT INTO TB_TURMAS (ID_TURMA, TURMA) VALUES ('1EF', '1º Ano do ensino fundamental I');
INSERT INTO TB_TURMAS (ID_TURMA, TURMA) VALUES ('2EF','2º Ano do ensino fundamental I');
INSERT INTO TB_TURMAS (ID_TURMA, TURMA) VALUES ('3EF','3º Ano do ensino fundamental I');
INSERT INTO TB_TURMAS (ID_TURMA, TURMA) VALUES ('4EF','4º Ano do ensino fundamental I');
INSERT INTO TB_TURMAS (ID_TURMA, TURMA) VALUES ('5EF','5º Ano do ensino fundamental I');

-- ENSINO FUNDAMENTAL II
INSERT INTO TB_TURMAS (ID_TURMA, TURMA) VALUES ('6EF', '6º Ano do ensino fundamental II');
INSERT INTO TB_TURMAS (ID_TURMA, TURMA) VALUES ('7EF', '7º Ano do ensino fundamental II');
INSERT INTO TB_TURMAS (ID_TURMA, TURMA) VALUES ('8EF', '8º Ano do ensino fundamental II');
INSERT INTO TB_TURMAS (ID_TURMA, TURMA) VALUES ('9EF', '9º Ano do ensino fundamental II');

-- ENSINO MÉDIO
INSERT INTO TB_TURMAS (ID_TURMA, TURMA) VALUES ('1EM', '1º Ano do ensino médio');
INSERT INTO TB_TURMAS (ID_TURMA, TURMA) VALUES ('2EM', '2º Ano do ensino médio');
INSERT INTO TB_TURMAS (ID_TURMA, TURMA) VALUES ('3EM', '3º Ano do ensino médio');

-- Verificando a tabela
SELECT * FROM TB_TURMAS;